---
title: "Ocean Health Index"
output: html_document
---
```{r}
library(tidyverse)
library(ggpubr)

data <- read.csv("scores.csv") # Dataframe: scores_2015.csv
# region <- read.csv() # Dataframe: regions_2015.csv
scores <- data %>% filter(dimension == "score") 

all.data <- scores %>% 
  rename(label = region_name)
global.data <- filter(all.data, label == "Global average")
eritrea.data <- filter(all.data, label == "Eritrea")
islands.data <- filter(all.data, label == "Prince Edward Islands")
sub.data <- filter(all.data, label %in% c( "Prince Edward Islands", "Global", "Eritrea"))
```

### Check the spread of the data ###

```{r}
hist.plot <- function(data){ 
          ggplot(data, aes(value, group = label)) + 
          geom_histogram(color = "grey40", fill = "grey50") +
          xlab("Score") + ylab("Count") + facet_wrap(scenario ~.) +
          # scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5)) +
          theme(panel.background = element_rect(fill = "white", colour = "white"), 
                legend.key.height = unit(1.2, "line"),
                legend.position = c(1.16, 0.49), # left/right, up/down
                legend.title = element_blank(),
                legend.background = element_blank(),
                legend.text = element_text(size = 8),
                axis.line = element_line(),
                axis.title = element_text(face = "bold"),
                strip.background = element_blank(),
                strip.text = element_text(face = "bold"),
                plot.margin = unit(c(0.4, 1.9, 0, 0),"cm"), # top, left, bottom, right
                axis.text.y = element_text(size = 8, family = "Helvetica"),
                axis.text.x = element_text(size = 8, family = "Helvetica"),
                axis.title.x = element_text(size = 9, family = "Helvetica"),
                axis.title.y = element_text(size = 9, family = "Helvetica"))
}

# Show each plot
subset <- filter(global.data, scenario == c("2012", "2013"))
global.plot <- hist.plot(subset)
global.plot

eritrea.plot <- hist.plot(eritrea.data)
eritrea.plot

islands.plot <- hist.plot(islands.data)
islands.plot
```


### Code to calcualte each intervals method ###

## 1) Quantiles ##

```{r}
eco.data = sub.data

calcOHIQuantiles <- function(eco.data) {

  index <- eco.data %>% filter(goal == "Index") %>% rename(index = value)
  
  grouped.data <- eco.data %>% filter (goal != "Index")  %>% na.omit() %>% group_by(scenario, label)
  
  # Sum category weights for each group, calculate number of ecosystems per group
  quantiles <- summarise(grouped.data, 
                              upper = quantile(value, probs = 0.75), 
                              lower = quantile(value, probs = 0.25), 
                              range = upper - lower)
  
  # Merge index and intervals
  index.scores <- merge(index, quantiles)
  
  return(index.scores)
}
```

## 2) Median Absolute deviation and Mean Absolute Deviation

```{r MAD}
calcOHIMAD <- function(eco.data) {
  
  index <- eco.data %>% filter(goal == "Index") %>% select(scenario, value, label) %>% rename(index = value)
  
  filter.data <- eco.data %>% filter (goal != "Index") #%>% group_by(scenario)
  
  index.scores <- merge(index, filter.data)
 
  # Calculate absolute diffs
  med.diff <- index.scores %>% mutate(abs.diff.OHI = abs(value - index)) %>% na.omit()# absolute diff from RLI

  grouped.data <- group_by(med.diff, scenario, label)
  
  measures <- summarise(grouped.data,
                        MedAD = median(abs.diff.OHI), # median absolute difference
                        MeanAD = mean(abs.diff.OHI)) # the name of a function to be used as center

  out.put <- merge(index, measures)

  intervals <- out.put %>% mutate(
                        lower.MedAD = index - MedAD, upper.MedAD = index + MedAD,
                        lower.MeanAD = index - MeanAD, upper.MeanAD = index + MeanAD, 
                        range.MedAD = upper.MedAD - lower.MedAD, 
                        range.MeanAD = upper.MeanAD - lower.MeanAD) %>%
                    as.data.frame()
}
```

## 3) Standard deviation

```{r SD}
calcOHIstd <- function(eco.data) {
  
  index <- eco.data %>% filter(goal == "Index") %>% select(scenario, value, label) %>% rename(index = value)
  
  filter.data <- scores %>% filter (goal != "Index") #%>% group_by(scenario)
  
  index.scores <- merge(index, filter.data)
 
  grouped.data <- group_by(index.scores, scenario, label)

  measures <- grouped.data %>% mutate(dev = value - index) %>% na.omit() %>%
              summarise(total.count = n(),
                         sd = sqrt((sum((dev)^2))/(total.count - 1))) # when you have a sample of the pop

  index.measures <- merge(measures, index)

  out.put <- index.measures %>% group_by(scenario) %>%
              mutate(lower = index - (0.67 * sd), upper = index + (0.67 * sd), # SD interval = 50% of data
                     range = upper - lower)
}
```

### Calculate intervals ###

```{r}
quantiles <- calcOHIQuantiles(sub.data)
mad <- calcOHIMAD(sub.data)
stdev <- calcOHIstd(sub.data)
```

# Subset ###

```{r}
MedAD <- select(mad, scenario, index, label, contains("Med"))
MeanAD <- select(mad, scenario, index,label, contains("Mean")) 
MedAD$Measure <- "MadAD"
MeanAD$Measure <- "MeanAD" 
colnames(MedAD)[5:6] <- c("lower", "upper")
colnames(MeanAD)[5:6] <- c("lower", "upper")
MedAD <- MedAD[-c(8)]
MeanAD <- MeanAD[-c(8)]
```

### Plots ###

### Generic Plot - no intervals ###

```{r plot}
base.plot <- function(eco.data, upper, lower, min, max){
  
  # Set dodge position
  pos <- position_dodge(width = 0.5)

  # Plot data
  ggplot(eco.data, aes(x = scenario, y = index, group = factor(label))) +
            geom_point(aes(colour = factor(label)),position = pos, size = 0.5) + #
            geom_line(aes(colour = factor(label)), position = pos, size = 0.3)+
            scale_color_manual(values = c("navy", "seagreen3", "skyblue2")) + # change lines/points
            scale_fill_manual(values = c("navy", "seagreen3", "skyblue2")) + # change ribbons 
            coord_cartesian(ylim = c(0, 100)) +
            xlab("Year") + 
            ylab("Ocean Health Index") +
  scale_x_continuous(breaks = c(2012, 2013, 2014, 2015)) +
  scale_y_continuous(limits = c(min, max), expand = c(0, 0), breaks = seq(0, 100, 25)) +
  # geom_hline(yintercept = 100, linetype = "dashed", color = "grey") +
  theme(axis.line = element_line(colour="black"),
        axis.ticks.y = element_blank(),
        # axis.text.y = element_text(size = 10, family = "Helvetica"),
        # axis.text.y = element_blank(),
        axis.text.x = element_text(size = 9, family = "Helvetica"),
        axis.title.x = element_text(size = 9, face = "bold", family = "Helvetica"),
        axis.title.y = element_text(size = 9, face = "bold", family = "Helvetica"),
        legend.key = element_blank(),
        legend.box = "horizontal",
        legend.title = element_blank(),
        panel.spacing = unit(1.5, "lines"),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}
```

### Generic Plot - with intervals ###

```{r plot}
int.plot <- function(eco.data, upper, lower, min, max){
  
  # Set dodge position
  pos <- position_dodge(width = 0.5)

  # Plot data
  ggplot(eco.data, aes(x = scenario, y = index, group = factor(label))) +
            geom_point(aes(colour = factor(label)),position = pos, size = 0.5) + #
            geom_line(aes(colour = factor(label)), position = pos, size = 0.3)+
    geom_ribbon(aes(ymax = lower, ymin = upper, fill = factor(label)), #position = pos,
                alpha = 0.3, position = pos) +
            scale_color_manual(values = c("navy", "seagreen3", "skyblue2")) + # change lines/points
            scale_fill_manual(values = c("navy", "seagreen3", "skyblue2")) + # change ribbons
            coord_cartesian(ylim = c(0, 100)) +
            xlab("Year") + 
            ylab("Ocean Health Index") +
  scale_x_continuous(breaks = c(2012, 2013, 2014, 2015)) +
  scale_y_continuous(limits = c(min, max), expand = c(0, 0), breaks = seq(0, 100, 25)) +
  theme(axis.line = element_line(colour="black"),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(size = 9, family = "Helvetica"),
        axis.title.x = element_text(size = 9, face = "bold", family = "Helvetica"),
        axis.title.y = element_text(size = 9, face = "bold", family = "Helvetica"),
        legend.key = element_blank(),
        legend.box = "horizontal",
        legend.title = element_blank(),
        panel.spacing = unit(1.5, "lines"),
        legend.position = "none",
        panel.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}
```
## Run plots ##

```{r}
no_plot <- base.plot(stdev, min = 0, max = 200) 
sd_plot <- int.plot(stdev,  upper = "upper", lower = "lower", min = 0, max = 200) 
quant_plot <- int.plot(quantiles,  upper = "upper", lower = "lower", min = 0, max = 130) 
MeanAD_plot <- int.plot(MeanAD,  upper = "upper", lower = ".ower", min = 0, max = 130)  
MedAD_plot <- int.plot(MedAD,  upper = "upper", lower = "lower", min = 0, max = 130)

ggarrange(no_plot, quant_plot, MedAD_plot, MeanAD_plot, sd_plot, 
          labels = c("   a) No intervals", "b) Quantiles (50% data)", "c) Median absolute dev.",
          "d) Mean absolute dev.", "e) Standard dev. (~50% data)"),
          font.label = list(size = 9, color = "black", family = "Helvetica"),
          ncol = 3, nrow = 2)
```