---
title: "Overlapping species AOH with feed crops"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

Load libraries

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(data.table)
library(dtplyr)
library(terra)
library(raster)
library(parallel)
library(rnaturalearth)
library(strex)
library(janitor)
library(rredlist)
library(sf)
library(basemaps)
library(tools)

source(here("src/directories.R"))

source(here("src/spatial.R"))

select <- dplyr::select


aoh_dir <- file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected/")
```

Bind all chunked data together, tidy, and save

```{r}

overlay_df <- purrr::map_df(list.files(here("prep/03_prep_spp_habitats/int/aoh_overlay_chunks_terrestrial/"), full.names = TRUE), readRDS) %>% 
  filter(!(ingredient %in% c("forage fish_fish meal", "forage fish_fish oil", "trimmings fish_fish meal, cut offs", "trimmings fish_fish oil, cut offs"))) # filter out marine ingredients, as there should be no overlap.. this is just a mistake from the last run

length(unique(overlay_df$sciname)) # 18558 - perfect! 

# now lets clean up the data a bit 

mammals_list <- read.csv(here("prep/data/Mammals_list_AOH.csv")) %>%
  dplyr::select(sciname = BINOMIAL, order = ORDER, iucn_rl_cat = Red_List_Category_2019)

birds_list <- read.csv(here("prep/data/Birds_list_AOH.csv")) %>%
    dplyr::select(sciname = BINOMIAL, order = Order_, iucn_rl_cat = F2019_Iucn_Red_List_Category)

all_spp_list <- rbind(mammals_list, birds_list)


overlay_df_tidy <- overlay_df %>%
  rename(aoh_filename = sciname) %>%
  separate(aoh_filename, into = c("first", "second", "bird_type"), sep = "_", remove = FALSE) %>%
  mutate(sciname = paste(first, second)) %>%
  mutate(aoh_filepath = paste0(aoh_dir, aoh_filename), 
         feed_filepath = sprintf(here("prep/02_feed/output/resampled/%s/%s_%s_A.tif"), diet, ingredient, allocation)) %>%
  dplyr::select(aoh_filename, sciname, bird_type, diet, allocation, ingredient, aoh_overlap, aoh_area_orig, feed_filepath, aoh_filepath) %>%
  left_join(all_spp_list, by = c("sciname")) %>%
  mutate(aoh_overlap = ifelse(is.na(aoh_overlap), 0, aoh_overlap))

species_list <- c(unique(overlay_df_tidy$sciname))

writeLines(species_list, here("prep/03_prep_spp_habitats/int/species_list.txt"))

```




Pull total amount of cropland (km2) for each allocation, diet, and aquafeed ingredient

```{r}
file_list <- list.files(here("prep/02_feed/output/resampled"), full.names = TRUE, recursive = TRUE, pattern = "_A") # 36 - good

rast_list <- rast(file_list)

names_list <- basename(file_list)


crops_km2 <- data.frame(feed_filepath = file_list, filename = names_list, total_cropland = global(rast_list, "sum", na.rm = TRUE)) %>%
  mutate(allocation = str_after_last(str_before_last(filename, "_"), "_"),
         ingredient = str_before_nth(filename, "_", 2),
         diet = str_after_last(str_before_last(feed_filepath, "\\/"), "\\/")) %>%
  dplyr::select(-filename) %>%
  rename(total_ingredient_km2 = sum)


```


Bind species' tolerances to the full aoh affected dataframe. Calculate actual amount of AOH that is affected by cropland, based on their habitat preferences. 

```{r}
mammals_list <- read.csv(here("prep/data/Mammals_list_AOH.csv"))

birds_list <- read.csv(here("prep/data/Birds_list_AOH.csv"))

ag_suitability <- readRDS(here("prep/03_prep_spp_habitats/int/terrestrial_spp_habitat_suitability.rds"))

aoh_df <- overlay_df_tidy %>%
  left_join(., ag_suitability, by = c("sciname" = "species")) %>%
  mutate(aoh_affected = aoh_overlap*(1 - cropland_suitability)) %>%
  left_join(crops_km2) %>%
  mutate(order = ifelse(is.na(order), "CHIROPTERA", order), # fix the spp with missing order
         spp_type = ifelse(order %in% c(mammals_list$ORDER), "Terrestrial mammal", "Bird")) %>% # identifier for class type
  dplyr::select(-order) %>%
  rename(suitability = cropland_suitability)

saveRDS(aoh_df, here("prep/03_prep_spp_habitats/output/aoh_terrestrial_mammals_birds_overlap.rds")) # save rds to save space

```

  
Do some checks: 

```{r}
check_bird <- aoh_df %>%
  filter(sciname == "Accipiter brevipes")

check_aoh_1 <- rast("/mnt/rdsi/raw_data/AOH_lumbierres/reprojected/Accipiter_badius_B.tif") %>%
  filter(ex_Accipiter_badius_B != 0)
plot(check_aoh_1)
check_aoh_2 <- rast("/mnt/rdsi/raw_data/AOH_lumbierres/reprojected/Accipiter_badius_R.tif") %>%
    filter(ex_Accipiter_badius_R != 0)
plot(check_aoh_2)
check_aoh_3  <- rast("/mnt/rdsi/raw_data/AOH_lumbierres/reprojected/Accipiter_badius_N.tif") %>%
    filter(ex_Accipiter_badius_N != 0)
plot(check_aoh_3)

check_intersect <- intersect(check_aoh_1, check_aoh_2)
plot(check_intersect)
check_intersect <- intersect(check_aoh_1, check_aoh_3)
plot(check_intersect)
check_intersect <- intersect(check_aoh_2, check_aoh_3)
plot(check_intersect) # ok so looks like there is no/minimal intersection... additionally, the paper indicates that they can be combined and are separate, non-overlapping habitats. So probably no double counting occurring thankfully. 

  
check <- aoh_df %>%
  filter(aoh_affected >= total_cropland) # 0, makes sense! 
```

  