---
title: "Summary plots"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

Load libraries

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(data.table)
library(terra)
library(raster)
library(rnaturalearth)
library(strex)
library(janitor)
library(sf)
library(tools)
library(rredlist)

source(here("src/directories.R"))

source(here("src/spatial.R"))

select <- dplyr::select


aoh_dir <- file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected/")

base_rast <- rast(res=0.5)
ext(base_rast) <- c(-180, 180, -90, 90)
```


Read in marine and terrestrial dfs and combine

```{r}
marine_overlap <- readRDS(here("prep/03_prep_spp_habitats/output/aoh_marine_overlap.rds")) %>%
#  dplyr::select(-feed_filepath) %>%
  mutate(allocation = ifelse(allocation == "ge", "gross energy", allocation)) %>%
  mutate(spp_type = ifelse(spp_type == "Microorganisms", "Marine microorganisms", spp_type)) %>%
    mutate(spp_type = ifelse(spp_type == "Invertebrates", "Marine invertebrates", spp_type)) %>%
  mutate(spp_type = ifelse(spp_type == "Reptiles and amphibians", "Marine reptiles and amphibians", spp_type)) %>%
  mutate(suitability = vuln_rescale*vuln_depth) %>%
  dplyr::rename(aoh_affected = affected_depth_reg_vuln) %>% # change this according to affected method
  group_by(sciname, spp_type, diet, allocation, ingredient) %>%
  summarise(aoh_area_orig = mean(aoh_area_orig, na.rm = TRUE),
            suitability = mean(suitability, na.rm = TRUE), 
            aoh_overlap = sum(aoh_overlap, na.rm = TRUE),
            aoh_affected = sum(aoh_affected, na.rm = TRUE)) %>%
  dplyr::select(sciname, spp_type, diet, allocation, ingredient, aoh_area_orig, suitability, aoh_overlap, aoh_affected) %>%
  ungroup()
  
  ## biggest orig = 271017242


terrestrial_overlap <- readRDS(here("prep/03_prep_spp_habitats/output/aoh_terrestrial_mammals_birds_overlap.rds")) %>% 
  group_by(sciname, diet, allocation, ingredient, spp_type) %>%
  summarise(suitability = mean(suitability, na.rm = TRUE),
            aoh_overlap = sum(aoh_overlap, na.rm = TRUE),
            aoh_area_orig = mean(aoh_area_orig, na.rm = TRUE),
            aoh_affected = sum(aoh_affected, na.rm = TRUE),
            total_ingredient_km2 = mean(total_ingredient_km2, na.rm = TRUE)) %>%
  ungroup() %>%
    mutate(allocation = ifelse(allocation == "ge", "gross energy", allocation)) %>%
          # spp_depth_pos = NA) %>%
  dplyr::select(-total_ingredient_km2) 


all_overlap <- rbind(marine_overlap, terrestrial_overlap) %>%
  filter(spp_type != "Marine microorganisms") %>%
  mutate(persistence = ((aoh_area_orig - aoh_affected)/aoh_area_orig)^0.25) 

```

Lets make plots, just using economic allocation. 

```{r}
all_overlap <- rbind(marine_overlap, terrestrial_overlap) %>%
  filter(spp_type != "Marine microorganisms") %>%
  filter(allocation == "economic")


## total AOH affected   
summary_df <- all_overlap %>%
  group_by(diet, allocation, ingredient) %>%
  summarise(total_aoh_affected = sum(aoh_affected, na.rm = TRUE)) %>%
  ungroup()

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, total_aoh_affected, FUN = function(x) sum(x)))


ggplot(summary_df, aes(x = ordered_ingredient, y = total_aoh_affected)) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  facet_grid(diet~allocation, scales = "free_y") +
    coord_flip() +
  labs(title = "Global AOH Affected (39822 species)", x = "Raw material and Ingredient", y = expression(paste("Total AOH Affected (", km^{2}, ")"))) + 
      theme(axis.text.x = element_text(angle = -90, hjust = 1)) # Adjust the 'angle' value as needed


## Split by class total AOH
summary_df <- all_overlap %>%
  group_by(diet, allocation, ingredient, spp_type) %>%
  summarise(total_aoh_affected = sum(aoh_affected, na.rm = TRUE)) %>%
  ungroup() 

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, total_aoh_affected, FUN = function(x) sum(x)))

# good place to find hex colors: https://encycolorpedia.com/81938c
category_colors <- c("#ffd59a", # Bird 
                    "#1E90FF",   # Fish (Dodger Blue)
                    "#00CED1",   # Marine invertebrates (Dark Turquoise)
                    "#81938c",   # Marine mammal
                    "#5faf3b",   # Marine plant
                    "#ba9bb8", # Reptiles + amphibians 
                    "#97a356" # Terrestrial mammals
                    )  

ggplot(summary_df, aes(x = ordered_ingredient, y = total_aoh_affected, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
  facet_grid(diet ~ allocation, scales = "free_y") +
  labs(title = "Global AOH Affected (39822 species)", x = "Raw material and Ingredient", y = expression(paste("Total AOH Affected (", km^{2}, ")")), fill = NULL) +
  scale_fill_manual(values = category_colors) +
  theme_minimal() + 
  coord_flip()  + 
    theme(axis.text.x = element_text(angle = -90, hjust = 1)) # Adjust the 'angle' value as needed



## Split by class average AOH
summary_df <- all_overlap %>%
  group_by(diet, allocation, ingredient, spp_type) %>%
  summarise(mean_aoh_affected = mean(aoh_affected, na.rm = TRUE),
            sd_aoh_affected = sd(aoh_affected, na.rm = TRUE)) %>%
  ungroup() 

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, mean_aoh_affected, FUN = function(x) sum(x)))

ggplot(summary_df, aes(x = ordered_ingredient, y = mean_aoh_affected, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
# geom_errorbar(aes(ymin = mean_aoh_affected, ymax = mean_aoh_affected + sd_aoh_affected), position = position_dodge(width = 0.9), width = 0.25) + 
  facet_grid(diet ~ allocation, scales = "free_y") +
  labs(title = "Average AOH Affected (39822 species)", x = "Raw material and Ingredient", y = expression(paste("Average AOH Affected (", km^{2}, ")")), fill = NULL) +
    scale_fill_manual(values = category_colors) +
  theme_minimal() + 
  coord_flip() 



## Split by class average AOH .. 
summary_df <- all_overlap %>%
  group_by(diet, allocation, spp_type) %>%
  summarise(mean_aoh_affected = mean(aoh_affected, na.rm = TRUE),
            sd_aoh_affected = sd(aoh_affected, na.rm = TRUE),
            mean_aoh_orig = mean(aoh_area_orig, na.rm = TRUE)) %>%
  ungroup()

summary_df$spp_type <- with(summary_df, reorder(spp_type, mean_aoh_affected, FUN = function(x) sum(x)))


ggplot(summary_df, aes(x = spp_type, y = mean_aoh_affected, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
# geom_errorbar(aes(ymin = mean_aoh_affected, ymax = mean_aoh_affected + sd_aoh_affected), position = position_dodge(width = 0.9), width = 0.25) + 
  facet_grid(diet ~ allocation, scales = "free") +
  labs(x = "Raw material and Ingredient", y = expression(paste("Average AOH Affected (", km^{2}, ")")), fill = NULL) +
  theme_minimal() + 
    # scale_fill_manual(values = c("#00CED1", "#1E90FF",  "#5faf3b", "#81938c", "#97a356", "#ffd59a")) +
    labs(title = "Average AOH Affected (39822 species)", x = "Species Class", y = expression(paste("Average AOH Affected (", km^{2}, ")")), fill = NULL) +

  coord_flip()

```


Make species specific plots! 

Coragyps_atratus; Black Vulture have a lot of overlap with soy protein concentrate under plant-dominant and economic allocation.


```{r}
countries_shp <- ne_countries(scale = 110, returnclass = "sf") |> st_transform(crs(moll_template)) %>%
  filter(continent %in% c("North America", "South America"))

this_crop_ingredient_raster <- rast(here("prep/02_feed/output/resampled/plant-dominant/Soybean_soy protein concentrate_economic_A.tif"))
plot(this_crop_ingredient_raster)
global(this_crop_ingredient_raster, "sum", na.rm = TRUE) # 2795.964

this_spp_rast <- rast(list.files(file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected/"), full.names = TRUE, pattern = "Coragyps_atratus"))
plot(this_spp_rast)

spp_names <- file_path_sans_ext(basename(list.files(file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected/"), full.names = TRUE, pattern = "Coragyps_atratus")))

overlap_rast <- this_crop_ingredient_raster*this_spp_rast 

names(overlap_rast) <- "American Black Vulture"

plot(overlap_rast)
global(overlap_rast, "sum", na.rm = TRUE) # 1820.562


overlap_df <- as.data.frame(overlap_rast, xy = TRUE) %>%
  pivot_longer(cols = c(3), names_to = "species") %>%
  filter(value > 0) %>%
  mutate(aoh_orig = 100) %>%
  mutate(p = ((aoh_orig - value)/aoh_orig)^0.25)

names(this_spp_rast) <- "American Black Vulture"
spp_aoh_df <- as.data.frame(this_spp_rast, xy = TRUE) %>%
  pivot_longer(cols = c(3), names_to = "species")

# crop_df <- as.data.frame(crop(this_crop_ingredient_raster, vect(countries_shp)), xy = TRUE) 

## check what the vulnerability is for this species

hab_suitability <- readRDS(here("prep/03_prep_spp_habitats/int/spp_habitat_suitability.rds")) %>% 
  filter(species == "Coragyps atratus") #suitability is 0, meaning vulnerability is 1. 


ggplot() + 
  geom_sf(data = countries_shp, fill = "grey", colour = "white") + 
   geom_raster(data = spp_aoh_df %>% filter(value >0), aes( x= x, y = y), color = "green") +
   geom_raster(data = overlap_df %>% filter(value >0), aes( x= x, y = y, fill = value)) + 
  # facet_wrap(~species) +
  labs(fill = expression(paste(km^{2}, " impacted")), title = "How does SPC harvest affect AOH?", subtitle = "Economic allocation; Plant-Dominant; American Black Vulture", caption = "Black areas are the original AOH") + 
  scale_fill_gradientn(colors = (RColorBrewer::brewer.pal(n=9, name = "YlOrRd"))) +
  theme_minimal() +
      theme(
          axis.title = element_blank()) 

ggplot() + 
  geom_sf(data = countries_shp, fill = "grey", colour = "white") + 
   geom_raster(data = spp_aoh_df %>% filter(value >0), aes( x= x, y = y), color = "green") +
   geom_raster(data = overlap_df %>% filter(value >0), aes( x= x, y = y, fill = p)) + 
  # facet_wrap(~species) +
  labs(fill = "Likelihood of Persistence", title = "How does SPC harvest affect AOH?", subtitle = "Economic allocation; Plant-Dominant; American Black Vulture", caption = "Black areas are the original AOH") + 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=9, name = "YlOrRd"))) +
  theme_minimal() +
      theme(
          axis.title = element_blank()) 


```


Make a plot! 

Marine: Let's choose a species with lots of overlap

 

```{r}
countries_shp <- ne_countries(scale = 110, returnclass = "sf") |> st_transform(crs(moll_template))

this_ingredient_raster_pel <- rast(here("prep/02_feed/output/resampled/fish-dominant/forage fish_fish oil_economic_pelagic_bycatch_A.tif"))
plot(log(this_ingredient_raster_pel+1))
global(this_ingredient_raster_pel, "sum", na.rm = TRUE) # 328.1194

this_ingredient_raster_ben <- rast(here("prep/02_feed/output/resampled/fish-dominant/forage fish_fish oil_economic_benthic_bycatch_A.tif"))
plot(log(this_ingredient_raster_ben+1))
global(this_ingredient_raster_ben, "sum", na.rm = TRUE) # 766.9572

this_ingredient_raster <- this_ingredient_raster_pel + this_ingredient_raster_ben


aquamaps_dir <- file.path(rdsi_raw_data_dir, "aquamaps")
am_spp_depth_df <- read.csv(file.path(aquamaps_dir, "aquamaps_0.6_depth_prepped.csv"))

this_spp_rast <- am_spp_depth_df %>%
  filter(species == "mobula japanica") %>%
      mutate(presence = 1) %>%
  dplyr::select(CenterLong, CenterLat, presence) %>%
  rast(., type = "xyz", crs = base_rast)  %>%
  project(moll_template, method = "near")

plot(this_spp_rast)

## read in vulnerability values 
marine_overlap <-  readRDS(here("prep/03_prep_spp_habitats/output/aoh_marine_overlap.rds")) %>%
#  dplyr::select(-feed_filepath) %>%
  mutate(allocation = ifelse(allocation == "ge", "gross energy", allocation)) %>%
  mutate(spp_type = ifelse(spp_type == "Microorganisms", "Marine microorganisms", spp_type)) %>%
    mutate(spp_type = ifelse(spp_type == "Invertebrates", "Marine invertebrates", spp_type)) %>%
  mutate(spp_type = ifelse(spp_type == "Reptiles and amphibians", "Marine reptiles and amphibians", spp_type)) %>%
  mutate(vulnerability = reg_vuln) %>%
  filter(sciname == "Mobula japanica",
         allocation == "economic", 
         ingredient == "forage fish_fish oil", 
         diet == "fish-dominant")

overlap_rast_pel <- this_ingredient_raster_pel*this_spp_rast*1
global(overlap_rast_pel, "sum", na.rm = TRUE) # 8.977985
overlap_rast_ben <- this_ingredient_raster_ben*this_spp_rast*1
global(overlap_rast_ben, "sum", na.rm = TRUE) # 473.9052

overlap_rast <- overlap_rast_pel + overlap_rast_ben

overlap_df <- overlap_rast %>%
  as.data.frame(xy = TRUE) %>%
  mutate(species = "Spinetail devil ray")

plot(log(overlap_rast+1))
global(overlap_rast, "sum", na.rm = TRUE) # 202.0294

spp_aoh_df <- this_spp_rast %>%
  as.data.frame(xy = TRUE) %>%
  mutate(species = "Spinetail devil ray")


ggplot() + 
  geom_sf(data = countries_shp, fill = "grey", colour = "white") + 
   geom_raster(data = spp_aoh_df %>% filter(presence >0), aes( x= x, y = y), color = "green") +
   geom_raster(data = overlap_df %>% filter(area_fmfo_bycatch >0), aes( x= x, y = y, fill = area_fmfo_bycatch)) + 
  # facet_wrap(~species) +
  labs(fill = expression(paste(km^{2}, " impacted")), title = "How does fish oil harvest impact AOH?", subtitle = "Economic allocation; Fish-Dominant; Spinetail Devil Ray", caption = "Black areas are the original AOH") + 
  scale_fill_gradientn(colors = (RColorBrewer::brewer.pal(n=9, name = "YlOrRd"))) +
  theme_minimal() +
      theme(
          axis.title = element_blank()) 


overlap_df <- overlap_rast %>%
  as.data.frame(xy = TRUE) %>%
  mutate(species = "Spinetail devil ray") %>%
  filter(area_fmfo_bycatch > 0) %>%
  mutate(aoh_orig = 100) %>%
  mutate(p = ((aoh_orig - area_fmfo_bycatch)/aoh_orig)^0.25)

ggplot() + 
  geom_sf(data = countries_shp, fill = "grey", colour = "white") + 
   geom_raster(data = spp_aoh_df %>% filter(presence >0), aes( x= x, y = y), color = "green") +
   geom_raster(data = overlap_df %>% filter(area_fmfo_bycatch >0), aes( x= x, y = y, fill = p)) + 
  # facet_wrap(~species) +
  labs(fill = "Likelihood of Persistence", title = "How does fish oil harvest impact AOH?", subtitle = "Economic allocation; Fish-Dominant; Spinetail Devil Ray", caption = "Black areas are the original AOH") + 
  scale_fill_gradientn(colors = rev((RColorBrewer::brewer.pal(n=9, name = "YlOrRd")))) +
  theme_minimal() +
      theme(
          axis.title = element_blank()) 



```
  
  