---
title: "Process rasters across taxa"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

Load libraries

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(data.table)
library(terra)
library(raster)
library(rnaturalearth)
library(strex)
library(janitor)
library(sf)
library(tools)
library(rredlist)
library(glue)
library(RColorBrewer)

source(here("src/directories.R"))

source(here("src/spatial.R"))

select <- dplyr::select
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # set working directory to where this script is located
this_dir <- getwd()

aoh_dir <- file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected_csvs/")

base_rast <- rast(res=0.5)
ext(base_rast) <- c(-180, 180, -90, 90)

# read in xy cell_id lookup table for land and ocean
ocean_xy_moll <- readRDS(file.path(this_dir, "data/spatial/moll_template_ocean_xy.rds"))
land_xy_moll <- readRDS(here(this_dir, "data/spatial/moll_template_land_xy.rds"))

impact_maps_dir <- file.path(rdsi_dir, "biodiversity_impacts/output")

```

Process raster maps of taxon aggregated mean impacts 


```{r}
r_to_df <- function(f) {
  r <- terra::rast(f)
  df <- data.frame(val = as.vector(values(r)),
                   cell_id = 1:ncell(r)) %>%
    filter(!is.na(val))
  return(df)
}

combine_taxa_maps <- function(tx_bycatch_map_df) {
  
  mean_fs <- tx_bycatch_map_df %>% filter(p == 'mean') %>% .$f
  sdev_fs <- tx_bycatch_map_df %>% filter(p == 'sdev') %>% .$f
  nspp_fs <- tx_bycatch_map_df %>% filter(p == 'nspp') %>% .$f
  taxa <- tx_bycatch_map_df$t %>% unique()
  
  message('... loading mean maps across taxa for bycatch...')
  mean_df <- parallel::mclapply(mean_fs, mc.cores = 12, FUN = r_to_df) %>%
    setNames(taxa) %>%
    data.table::rbindlist(idcol = 'taxon') %>%
    rename(imp_mean = val)
  
  message('... loading std dev maps across taxa for bycatch...')
  sdev_df <- parallel::mclapply(sdev_fs, mc.cores = 12, FUN = r_to_df) %>%
    setNames(taxa) %>%
    data.table::rbindlist(idcol = 'taxon') %>%
    rename(imp_sdev = val)
  
  message('... loading nspp maps across taxa for bycatch...')
  nspp_df <- parallel::mclapply(nspp_fs, mc.cores = 12, FUN = r_to_df) %>%
    setNames(taxa) %>%
    data.table::rbindlist(idcol = 'taxon') %>%
    rename(imp_nspp = val)
  
  message('... joining mean, sd, nspp into big-ass dataframe for bycatch...')
  big_df <- mean_df %>%
    full_join(sdev_df, by = c('taxon', 'cell_id')) %>%
    full_join(nspp_df, by = c('taxon', 'cell_id'))
  
  return(big_df)
}

process_mean_rasts <- function(big_df) {
  ### Set up for parallel processing
  cell_id_vec <- big_df$cell_id %>% unique()
  n_gps <- 25
  gp_vec <- rep(1:n_gps, length.out = length(cell_id_vec))
  
  ### perform parallel processing
  spp_mean_list <- parallel::mclapply(
    X = 1:n_gps, mc.cores = 12, 
    FUN = function(gp) { ### gp <- 1
      gp_cells <- cell_id_vec[gp_vec == gp]
      message('...processing ', length(gp_cells), ' cells in group ', gp, '...')
      gp_out <- big_df %>%
        filter(cell_id %in% gp_cells) %>%
        group_by(cell_id) %>%
        summarize(imp_mean = (sum(imp_mean * imp_nspp) / sum(imp_nspp)))
    })
  
  ### gather results
  spp_mean_df <- data.table::rbindlist(spp_mean_list)
  return(spp_mean_df)
}
```


```{r assemble taxon impact maps to total maps}


tx_bycatch_map_df <- data.frame(f = list.files(dirname(impact_maps_dir), 
                                               pattern = 'imp_unwt_',
                                               full.names = TRUE, recursive = TRUE)) %>%
  mutate(t = str_extract(basename(f), paste0(taxa, collapse = '|')),
         p = str_extract(basename(f), '_mean|_sdev|_nspp') %>% str_remove('_'))

impact_map_stem <- here_anx('_output/impact_maps/impact_maps_species', 
                        'impact_spp_bycatch_%s.tif')
  ### %s is parameter (mean, sd, nspp)

### check if total stressor maps are complete
impact_f_mean <- sprintf(impact_map_stem, 'mean')
impact_f_sdev <- sprintf(impact_map_stem, 'sdev')
```




```{r}
allocation_types <- c("mass")
impact_type = "mean"
diet_types <- c("plant-dominant", "fish-dominant")

for(allocation in allocation_types){
  for(diet in diet_types){
  
    # allocation = "ge"
    # diet = "plant-dominant"
    
    files <- list.files(impact_maps_dir, pattern = sprintf("imp_unwt_.*_%s_.*_%s\\.tif", allocation, impact_type), recursive = TRUE, full.names = TRUE)
    

files <- files[grep(diet, files)]
   
     rasters_list <- lapply(files, function(raster_file) {
  raster_obj <- rast(raster_file)
  crs(raster_obj) <- crs(moll_template)
  raster_obj <- project(raster_obj, moll_template)
  return(raster_obj)
})
     
 rasters <- rast(rasters_list)
rast_names <- str_remove_all(str_remove_all(str_after_nth(basename(files), "_", 2), paste0("_", allocation)), paste0("_", impact_type, ".tif")) 
    

names(rasters) <- rast_names
rasters[rasters == 0] <- NA

my_palette <- c("#FED976",  "#FEB24C", "#FD8D3C", "#FC4E2A", "#E31A1C",
"#BD0026", "#800026")
scales::show_col(my_palette)


test <- rasters %>% 
  as.data.frame(xy=TRUE) %>%
  pivot_longer(names_to = "type", values_to = "value", cols = c(3:ncol(.)))
 #  pivot_longer(names_to = "type", values_to = "value", cols = c(3:80))
   # pivot_longer(names_to = "type", values_to = "value", cols = c(3:64))


for(plot_type in unique(test$type)){

  # plot_type = "CropsNES_coconut oil_Bird"
  
ggplot(data = test %>% filter(type == plot_type)) +
  geom_tile(aes(x = x, y = y, fill = value)) + 
    scale_fill_gradientn(colors = my_palette) +
    labs(title = glue("{plot_type}"))

 ggsave(glue(file.path(this_dir, "int/plots/{diet}/{allocation}/{impact_type}_{plot_type}.png")), units=c("in"))

}


  }
}





```

