---
title: "Summary plots"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup

Load libraries

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(data.table)
library(terra)
library(raster)
library(rnaturalearth)
library(strex)
library(janitor)
library(sf)
library(tools)
library(khroma)
library(scales)
library(fields)
library(patchwork)
library(cowplot)
library(glue)
library(viridis)

source(here("src/directories.R"))

source(here("src/spatial.R"))

select <- dplyr::select
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # set working directory to where this script is located
this_dir <- getwd()

aoh_dir <- file.path(rdsi_raw_data_dir, "AOH_lumbierres/reprojected_csvs/")

base_rast <- rast(res=0.5)
ext(base_rast) <- c(-180, 180, -90, 90)

biodiv_dir <- file.path(rdsi_dir, "biodiversity_impacts")

impact_maps_dir <- file.path(biodiv_dir, "output")


```


```{r establish color palettes}

## establish color palette from food footprint project
d_brown <- "#515256"
m_brown <- "#B27B54"
l_brown <- "#BC995F"
green <- "#A8B072"
yellow<- "#EFCE71"
l_yellow <- "#F7F6C1"

jv_pal <- c(l_yellow, yellow, green, l_brown, m_brown, d_brown)

continuous_pal <-  colorRampPalette(jv_pal, space="Lab", bias = 3.5)(10000)
image(volcano, asp=1, col=continuous_pal)

light_gray <- "#F8F9FA"
final_palette <- c(light_gray, continuous_pal)
image(volcano, asp=1, col=final_palette)

palette_red <- c(final_palette, "#B90000")
image(volcano, asp=1, col=palette_red)

# jv_pal_new <- jv_pal[7000:length(continuous_pal)]
# image(volcano, asp=1, col=jv_pal_new)

light_gray <- "#F8F9FA"
final_palette <- c(light_gray, continuous_pal)
scales::show_col(final_palette)

countries_shp <- ne_countries(scale = 110, returnclass = "sf") |> 
  st_transform(crs(moll_template)) # read in countries shapefile

```



Read in marine and terrestrial dfs and combine

```{r}
marine_overlap <- readRDS(here("prep/03_prep_spp_habitats/output/aoh_marine_impact.rds")) %>%
  group_by(sciname, spp_type, diet, fcr_type, allocation, ingredient) %>%
  summarise(vulnerability = mean(vulnerability, na.rm = TRUE), 
            impact_total = sum(impact_total, na.rm = TRUE)) %>%
  ungroup() %>%
    dplyr::select(sciname, spp_type, diet, fcr_type, allocation, ingredient, vulnerability, impact_total)


terrestrial_overlap <- readRDS(here("prep/03_prep_spp_habitats/output/aoh_terrestrial_mammals_birds_impact.rds")) %>% 
  group_by(sciname, diet, fcr_type, allocation, ingredient, spp_type) %>%
  summarise(vulnerability = 1 - mean(suitability, na.rm = TRUE),
            impact_total = sum(impact_total, na.rm = TRUE)) %>%
  ungroup() %>%
    dplyr::select(sciname, spp_type, diet, fcr_type, allocation, ingredient, vulnerability, impact_total)

all_overlap <- rbind(marine_overlap, terrestrial_overlap)

```

Maps!

Global maps across ingredients and taxon; Delta plots as well

```{r}


## only need to save RDS when impact maps info has changed
allocations <- c("economic", "ge", "mass")

# for(allocation_type in allocations){
# 
#  # allocation_type = "mass"
# 
# global_maps_list <- list.files(file.path(impact_maps_dir, "impact_maps_across_taxon_ingredient"), pattern = allocation_type, recursive = TRUE, full.names = TRUE)
# 
# global_maps_mean <- rast(global_maps_list)
# names(global_maps_mean) <- file_path_sans_ext(str_after_nth(global_maps_list, "\\/", 6))
# 
# 
# all_df <- as.data.frame(global_maps_mean, xy = TRUE) %>%
#   pivot_longer(cols = c(3:ncol(.)), values_to = "value", names_to = "type") %>%
#   separate_wider_delim(type, delim = "/", names = c("diet", "fcr_type", "calc_type")) %>%
#   mutate(value =  ifelse(str_detect(calc_type, "mean"), log(value*1000000 + 1), value)) %>%
#   rename(long = x, lat = y)
# 
# for(i in unique(all_df$calc_type)){
# 
#   # i = "economic_mean"
# 
#   loop_df <- all_df %>%
#     filter(calc_type == i) %>%
#     filter(!is.na(value))
# 
# data.table::fwrite(loop_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_ingredient/{i}.rds.gz")))
# 
# }
# }



## make plots showing impacts for each scenario 

allocation_types <- c("mass", "economic", "ge")  
calc_types <- c("mean", "nspp", "sd")
types_df <- expand.grid(allocation_types, calc_types) %>%
  unite(new_var, Var1:Var2, sep = "_") %>%
  pull(new_var) %>%
  unique()

diets <- c("fish-dominant", "plant-dominant")
fcrs <- c("regular", "efficienct")

for(type in types_df){
  
  # type = "economic_mean"
  
 filepath <- glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_ingredient/{type}.rds.gz"))

loop_df <-  fread(filepath) # %>%
 # mutate(fcr_type = "regular")

# loop_df_2 <-  fread(filepath) %>%
#  mutate(fcr_type = "efficient")

# loop_df <- rbind(loop_df, loop_df_2)
  
## create maps in separate plots, force common scale between them
maps <- map(.x = diets, 
            .f = function(x, y) 
  ggplot() + 
  geom_tile(data = loop_df  %>% filter(diet == x), aes(x= long, y = lat, fill = value)) +  # (exp(value) - 1) / 1000000)
      # scale_fill_gradientn(colors = YlOrBr(9), na.value = "white") +  # Set the color for missing values (NA) to white
   scale_fill_gradientn(colors = final_palette, na.value = "white") +
   #  scale_fill_viridis(direction = -1) + 
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())
            )

ggsave(glue(here(this_dir, "output/plots/{type}_plot.png")), plot = plot_grid(plotlist = maps, labels = glue("{diets}:{type}"), label_size = 10, nrow = 2), width = 10, height = 8, bg = "white")


}


# create delta (change) plots between each diet scenario

for(type in types_df){
  
  # type = "economic_nspp"
  # 
  # if(file.exists(glue(here(this_dir, "output/plots/delta/{type}_plot.png")))){
  #   cat("exists")
  #   next()
  # }
  # 
 filepath <- glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_ingredient/{type}.rds.gz"))

delta_df <-  fread(filepath)
  
if(str_detect(type, "mean")){
  
  delta_df <- delta_df %>%
    mutate(value = (exp(value) - 1) / 1000000) %>%
      pivot_wider(names_from = c(diet), values_from = value) %>%
    mutate(`fish-dominant` = ifelse(is.na(`fish-dominant`), 0, `fish-dominant`),
           `plant-dominant` = ifelse(is.na(`plant-dominant`), 0, `plant-dominant`)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
  
}else{
    delta_df <- delta_df %>%
      pivot_wider(names_from = c(diet), values_from = value) %>%
          mutate(`fish-dominant` = ifelse(is.na(`fish-dominant`), 0, `fish-dominant`),
           `plant-dominant` = ifelse(is.na(`plant-dominant`), 0, `plant-dominant`)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
}
  
# data.table::fwrite(delta_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_ingredient/delta/{type}.rds.gz")))


  
if(str_detect(type, "nspp")){
  limit <- c(min(delta_df$delta), max(delta_df$delta))
  
}else{
limit <- c(quantile(delta_df$delta, 0.05), quantile(delta_df$delta, 0.9))

}

## create maps in separate plots, force common scale between them
  ggplot() + 
  geom_tile(data = delta_df %>% filter(delta != 0) , aes(x= long, y = lat, fill = delta)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,  limit = limit, na.value = "white", oob=scales::squish) + # this will make sure anything above the scales limit will be a solid color
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) + 
    labs(caption = str_replace(glue("{type}"), "_", "; "))
            

ggsave(glue(here(this_dir, "output/plots/delta/{type}_plot.png")), width = 10, height = 8, bg = "white")

}

test <- rast("/mnt/rdsi/biodiversity_impacts/output/impact_maps_across_taxon_ingredient/plant-dominant/regular/economic_mean.tif")
test2 <- rast("/mnt/rdsi/biodiversity_impacts/output/impact_maps_across_taxon_ingredient/fish-dominant/regular/economic_mean.tif")

test3 <- test2 - test

test3[test3 == 0] <- NA

plot(test3*1000000)
# seems to match

```

Global maps across ingredients per taxon 

```{r}

allocations <- c("economic", "ge", "mass")
calc_types <- c("mean", "sd", "nspp")
taxon <- all_overlap %>% filter(spp_type != "polychaetes") %>% pull(spp_type) %>% unique()

## this part only needs to be run if the source maps changed! 
# for(allocation_type in allocations){
#     for(taxa_type in taxon){
#       for(type in calc_types){
#
 # allocation_type = "economic"
 #  taxa_type = "sponges"
# 
#       out_fstem <- glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/{allocation_type}_{taxa_type}_{type}.rds.gz"))
# 
#       # if(file.exists(out_fstem)){
#       #
#       #   message(glue("skipping {allocation_type}_{taxa_type}_{type}"))
#       #   next()
#       #
#       # }
# 
# global_maps_list <- list.files(file.path(impact_maps_dir, "impact_maps_by_taxon_across_ingredient"), pattern = glue("{allocation_type}_{taxa_type}"), recursive = TRUE, full.names = TRUE)
# 
# stack_rast <- rast()

# for(file in global_maps_list){
#   # file <- global_maps_list[[1]]
# 
#   rast_1 <- rast(file) %>%
#     project(., moll_template, method = "near")
# 
#   stack_rast <- c(stack_rast, rast_1)
# }
# 
# names(stack_rast) <- file_path_sans_ext(str_after_nth(global_maps_list, "\\/", 6))
# 
# 
# all_df <- as.data.frame(stack_rast, xy = TRUE) %>%
#   pivot_longer(cols = c(3:ncol(.)), values_to = "value", names_to = "type") %>%
#   filter(!is.na(value)) %>%
#   separate_wider_delim(type, delim = "/", names = c("diet", "fcr_type", "taxa_calc_type")) %>%
#   separate_wider_delim(taxa_calc_type, delim = "_", names = c("allocation", "taxa", "calc_type")) %>%
#   mutate(value =  ifelse(str_detect(calc_type, "mean"), log(value*1000000 + 1), value)) %>%
#   rename(long = x, lat = y)
# 
# for(i in unique(all_df$calc_type)){
#   
#   # calc_type = "mean"
#   
#   # if(glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/{allocation_type}_{taxa_type}_{i}.rds.gz")) %in% c(unique(done$f))){
#   #   
#   #   cat("file exists")
#   #   next()
#   # }
# 
#   loop_df <- all_df %>%
#     filter(calc_type == i) %>%
#     filter(!is.na(value))
# 
#   data.table::fwrite(loop_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/{allocation_type}_{taxa_type}_{i}.rds.gz")))
# 
#       }
#     }
#   }
# }
     

# test <- data.frame(f = list.files(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient"), full.names = TRUE)) %>%
#   mutate(time = file.info(f)$ctime,
#          size = file.size(f)) # just a check to see everything ran if you can't view it on filezilla for some reason

  
# make and save plots across ingredients per taxon  

for(allocation_type in allocations){
    for(taxa_type in taxon){
      for(type in calc_types){

        # allocation_type = "economic"
        # taxa_type = "Bird"
        # type = "mean"
        
        all_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/{allocation_type}_{taxa_type}_{type}.rds.gz"))) %>%
          filter(!is.na(value))
        
diets <- unique(all_df$diet)
  
## create maps in separate plots, force common scale between them
maps <- map(.x = diets, 
            .f = function(x, y) 
  ggplot() + 
  geom_tile(data = all_df  %>% filter(diet == x), aes(x= long, y = lat, fill = value)) + 
      # scale_fill_gradientn(colors = YlOrBr(9), na.value = "white") +  # Set the color for missing values (NA) to white
   scale_fill_gradientn(colors = final_palette, na.value = "white") +
   #  scale_fill_viridis(direction = -1) + 
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) +
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())
            )


ggsave(glue(here(this_dir, "output/plots/by_taxa/{allocation_type}_{taxa_type}_{type}_plot.png")), plot = plot_grid(plotlist = maps, labels = glue("{diets}:{allocation_type}:{taxa_type}:{type}"), label_size = 10, nrow = 2), width = 10, height = 8, bg = "white")

    }
  }
}



# save delta plots across ingredients per taxon 

for(allocation_type in allocations){
    for(taxa_type in taxon){
      for(type in calc_types){
  
        # type = "mean"
        # allocation_type = "economic"
        # taxa_type = "arthropods"
  
  if(file.exists(glue(here(this_dir, "output/plots/delta/by_taxa/{allocation_type}_{taxa_type}_{type}_plot.png")))){
    cat("exists")
    next()
  }
  
        all_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/{allocation_type}_{taxa_type}_{type}.rds.gz"))) %>%
          filter(!is.na(value))

if(str_detect(type, "mean")){
  
  delta_df <- all_df %>%
    mutate(value = (exp(value) - 1) / 1000000) %>%
      pivot_wider(names_from = c(diet, taxa), values_from = value) %>%
    rename_with(
      ~ case_when(
        str_detect(., "fish-dominant") ~ "fish-dominant",
        str_detect(., "plant-dominant") ~ "plant-dominant",
        TRUE ~ .)
      ) %>%
    mutate(`fish-dominant` = ifelse(is.na(`fish-dominant`), 0, `fish-dominant`),
           `plant-dominant` = ifelse(is.na(`plant-dominant`), 0, `plant-dominant`)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
  
}else{
    delta_df <- all_df %>%
      pivot_wider(names_from = c(diet, taxa), values_from = value) %>%
    rename_with(
      ~ case_when(
        str_detect(., "fish-dominant") ~ "fish-dominant",
        str_detect(., "plant-dominant") ~ "plant-dominant",
        TRUE ~ .)
      ) %>%
          mutate(`fish-dominant` = ifelse(is.na(`fish-dominant`), 0, `fish-dominant`),
           `plant-dominant` = ifelse(is.na(`plant-dominant`), 0, `plant-dominant`)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
}
  
# data.table::fwrite(delta_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_by_taxon_across_ingredient/delta/{allocation_type}_{taxa_type}_{type}.rds.gz")))

if(str_detect(type, "nspp")){
  limit <- c(min(delta_df$delta), max(delta_df$delta))
  
}else{
limit <- c(quantile(delta_df$delta, 0.05), quantile(delta_df$delta, 0.9))
}

## create maps in separate plots, force common scale between them
  ggplot() + 
  geom_tile(data = delta_df %>% filter(delta != 0) , aes(x= long, y = lat, fill = delta)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,  limit = limit, na.value = "white", oob=scales::squish) + # squish makes sure anything above the scales limit will be a solid red or blue... better to visualize this way since the numbers are so small
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) + 
    labs(caption = glue("{allocation_type}; {taxa_type}; {type}"))
            

ggsave(glue(here(this_dir, "output/plots/delta/by_taxa/{allocation_type}_{taxa_type}_{type}_plot.png")), width = 10, height = 8, bg = "white")

    }
  }
}
```

Global maps by ingredients across taxon 

```{r}

allocations <- c("economic", "ge", "mass")
calc_types <- c("mean", "sd", "nspp")
ingredients <- all_overlap %>% pull(ingredient) %>% unique()

## commented out code only needs to be run if the source impact maps are updated! 
# for(allocation_type in allocations){
#   for(ingredient_type in ingredients){
# 
#       # ingredient_type = "Soybean_soybean meal"
#       # allocation_type = "economic"
#       # type = "mean"
# 
# global_maps_list <- list.files(file.path(impact_maps_dir, "impact_maps_across_taxon_by_ingredient"), pattern = glue("{allocation_type}_{ingredient_type}"), recursive = TRUE, full.names = TRUE)
# 
# stack_rast <- rast()
# 
# for(file in global_maps_list){
#   # file <- global_maps_list[[1]]
# 
#   rast_1 <- rast(file) %>%
#     project(., moll_template, method = "near")
# 
#   stack_rast <- c(stack_rast, rast_1)
# }
# 
# names(stack_rast) <- file_path_sans_ext(str_after_nth(global_maps_list, "\\/", 6))
# 
# 
# all_df <- as.data.frame(stack_rast, xy = TRUE) %>%
#   pivot_longer(cols = c(3:ncol(.)), values_to = "value", names_to = "type") %>%
#   separate_wider_delim(type, delim = "/", names = c("diet", "fcr_type", "ingredient_calc_type")) %>%
#     separate_wider_delim(ingredient_calc_type, delim = "_", names = c("allocation", "raw_material", "ingredient", "calc_type")) %>%
#   mutate(value =  ifelse(str_detect(calc_type, "mean"), log(value*1000000 + 1), value)) %>%
#   rename(long = x, lat = y) %>%
#   filter(!is.na(value)) %>%
#   unite("crop_ingredient", c(raw_material:ingredient), sep = "_", remove = FALSE)
# 
# for(i in unique(all_df$calc_type)){
#   # i = "mean"
# 
#   loop_df <- all_df %>%
#     filter(calc_type == i) %>%
#     filter(!is.na(value))
# 
#   data.table::fwrite(loop_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient/{allocation_type}_{ingredient_type}_{i}.rds.gz")))
# 
#    }
#   }
# }
#
# test <- data.frame(f = list.files(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient"), full.names = TRUE)) %>%
#   mutate(time = file.info(f)$ctime,
#          size = file.size(f)) 



for(allocation_type in allocations){
    for(ingredient_type in ingredients){
      for(type in calc_types){
        
      # ingredient_type = "Soybean_soybean meal"
      # allocation_type = "economic"
      # type = "mean"
        
                all_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient/{allocation_type}_{ingredient_type}_{type}.rds.gz"))) 
 
diets <- unique(all_df$diet)
  
## create maps in separate plots, force common scale between them
maps <- map(.x = diets, 
            .f = function(x, y) 
  ggplot() + 
  geom_tile(data = all_df  %>% filter(diet == x), aes(x= long, y = lat, fill = value)) + 
   scale_fill_gradientn(colors = final_palette, na.value = "white") +
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())
            )

ggsave(glue(here(this_dir, "output/plots/by_ingredient/{allocation_type}_{ingredient_type}_{type}_plot.png")), plot = plot_grid(plotlist = maps, labels = glue("{diets}:{allocation_type}:{ingredient_type}:{type}"), label_size = 10, nrow = 2), width = 10, height = 8, bg = "white")

    
    }
  }
}


# make delta plots! 

for(allocation_type in allocations){
    for(ingredient_type in ingredients){
      for(type in calc_types){
  
        # type = "mean"
        # allocation_type = "economic"
        # ingredient_type = "CropsNES_coconut oil"
  
  if(file.exists(glue(here(this_dir, "output/plots/delta/by_ingredient/{allocation_type}_{ingredient_type}_{type}_plot.png")))){
    cat("exists")
    next()
  }
  
        all_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient/{allocation_type}_{ingredient_type}_{type}.rds.gz"))) %>%
          filter(!is.na(value)) %>%
          dplyr::select(long, lat, fcr_type, allocation, crop_ingredient, calc_type, diet, value) %>%
          filter(crop_ingredient == ingredient_type)

if(str_detect(type, "mean")){
  
  delta_df <- all_df %>%
    mutate(value = (exp(value) - 1) / 1000000) %>%
      pivot_wider(names_from = c(diet, crop_ingredient), values_from = value) %>%
    rename_with(
      ~ case_when(
        str_detect(., "fish-dominant") ~ "fish-dominant",
        str_detect(., "plant-dominant") ~ "plant-dominant",
        TRUE ~ .)
      ) 
  
  if(!("fish-dominant" %in% c(colnames(delta_df)))){
    
    delta_df <- delta_df %>%
      mutate(`fish-dominant` = 0)
  }else if(!("plant-dominant" %in% c(colnames(delta_df)))){
        delta_df <- delta_df %>%
      mutate(`plant-dominant` = 0)
  }
  
  delta_df <- delta_df %>% 
  mutate(`fish-dominant` = coalesce(`fish-dominant`, 0),
         `plant-dominant` = coalesce(`plant-dominant`, 0)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
  
}else{
    delta_df <- all_df %>%
      pivot_wider(names_from = c(diet, crop_ingredient), values_from = value) %>%
    rename_with(
      ~ case_when(
        str_detect(., "fish-dominant") ~ "fish-dominant",
        str_detect(., "plant-dominant") ~ "plant-dominant",
        TRUE ~ .)
      ) 
  
  if(!("fish-dominant" %in% c(colnames(delta_df)))){
    
    delta_df <- delta_df %>%
      mutate(`fish-dominant` = 0)
  }else if(!("plant-dominant" %in% c(colnames(delta_df)))){
        delta_df <- delta_df %>%
      mutate(`plant-dominant` = 0)
  }
  
  delta_df <- delta_df %>% 
  mutate(`fish-dominant` = coalesce(`fish-dominant`, 0),
         `plant-dominant` = coalesce(`plant-dominant`, 0)) %>%
  mutate(delta = (`fish-dominant` - `plant-dominant`)) %>%
    mutate(delta_log = log(delta + 1)) %>%
    mutate(delta_rescale = delta*1000000)
}
  
  
#   data.table::fwrite(loop_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient/{allocation_type}_{ingredient_type}_{type}.rds.gz")))

        
if(str_detect(type, "nspp")){
  limit <- c(min(delta_df$delta), max(delta_df$delta))
  
}else{
limit <- c(quantile(delta_df$delta, 0.05), quantile(delta_df$delta, 0.9))
}

## create maps in separate plots, force common scale between them
  ggplot() + 
  geom_tile(data = delta_df %>% filter(delta != 0) , aes(x= long, y = lat, fill = delta)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,  limit = limit, na.value = "white", oob=scales::squish) +
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) + 
    labs(caption = glue("{allocation_type}; {ingredient_type}; {type}"))
            

ggsave(glue(here(this_dir, "output/plots/delta/by_ingredient/{allocation_type}_{ingredient_type}_{type}_plot.png")), width = 10, height = 8, bg = "white")

    }
  }
}

```

Global maps by raw material across taxon 

```{r}

allocations <- c("economic", "ge", "mass")
calc_types <- c("mean", "sd", "nspp")
ingredients <- all_overlap %>% pull(ingredient) %>% unique()
raw_mats <- all_overlap %>% mutate(raw_material = str_before_first(ingredient, "_")) %>% 
  pull(raw_material) %>% unique()

## commented out code only needs to be run if the source impact maps are updated! 
for(allocation_type in allocations){
  for(raw_mat in raw_mats){
    for(type in calc_types){

    # ingredient_type = "Soybean_soybean meal"
    # allocation_type = "economic"
    # type = "mean"
    #  raw_mat = "CropsNES"

    all_files <- list.files(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_ingredient"), pattern = glue("{allocation_type}_{raw_mat}_.*._{type}"), full.names = TRUE)


all_df <- map_dfr(all_files, ~fread(.x), header = TRUE)

all_df_fin <- all_df %>% 
  mutate(value = ifelse(calc_type == "mean", (exp(value) - 1) / 1000000, value)) %>%
  group_by(long, lat, diet, fcr_type, allocation, raw_material, calc_type) %>% 
  summarise(value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# test <- all_df_fin %>% group_by(diet, fcr_type, allocation) %>% summarise(sum = sum(value, na.rm = TRUE))


data.table::fwrite(all_df_fin, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_raw_material/{allocation_type}_{raw_mat}_{type}.rds.gz")))


delta_df <- all_df_fin %>%
        pivot_wider(names_from = c(diet), values_from = value) 


  if(!("fish-dominant" %in% c(colnames(delta_df)))){
    
    delta_df <- delta_df %>%
      mutate(`fish-dominant` = 0)
  }else if(!("plant-dominant" %in% c(colnames(delta_df)))){
        delta_df <- delta_df %>%
      mutate(`plant-dominant` = 0)
  }

delta_df <- delta_df %>% 
  mutate(delta = (`fish-dominant` - `plant-dominant`)) 

data.table::fwrite(delta_df, glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_raw_material/delta/{allocation_type}_{raw_mat}_{type}.rds.gz")))

    }
  }
}



for(allocation_type in allocations){
    for(raw_mat in raw_mats){
      for(type in calc_types){
        
      # raw_mat = "forage fish"
      # allocation_type = "economic"
      # type = "nspp"
      
                all_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_raw_material/{allocation_type}_{raw_mat}_{type}.rds.gz"))) 
 
diets <- unique(all_df$diet)
  
## create maps in separate plots, force common scale between them
maps <- map(.x = diets, 
            .f = function(x, y) 
  ggplot() + 
  geom_tile(data = all_df  %>% filter(diet == x), aes(x= long, y = lat, fill = value)) + 
   scale_fill_gradientn(colors = final_palette, na.value = "white") +
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank())
            )

ggsave(glue(here(this_dir, "output/plots/by_material/{allocation_type}_{raw_mat}_{type}_plot.png")), plot = plot_grid(plotlist = maps, labels = glue("{diets}:{allocation_type}:{raw_mat}:{type}"), label_size = 10, nrow = 2), width = 10, height = 8, bg = "white")

    
    }
  }
}


# make delta plots! 

for(allocation_type in allocations){
    for(raw_mat in raw_mats){
      for(type in calc_types){
  
        # type = "mean"
        # allocation_type = "economic"
        # raw_mat = "Soybean"
  
  # if(file.exists(glue(here(this_dir, "output/plots/delta/by_ingredient/{allocation_type}_{ingredient_type}_{type}_plot.png")))){
  #   cat("exists")
  #   next()
  # }
  
        delta_df <- fread(glue(file.path(impact_maps_dir, "csvs/impact_maps_across_taxon_by_raw_material/delta/{allocation_type}_{raw_mat}_{type}.rds.gz"))) %>%
          filter(!is.na(delta)) %>%
          dplyr::select(long, lat, fcr_type, allocation, raw_material, calc_type, delta)
  
if(str_detect(type, "nspp")){
  limit <- c(min(delta_df$delta), max(delta_df$delta))
  
}else{
limit <- c(quantile(delta_df$delta, 0.05), quantile(delta_df$delta, 0.9))
}

## create maps in separate plots, force common scale between them
  ggplot() + 
  geom_tile(data = delta_df %>% filter(delta != 0) , aes(x= long, y = lat, fill = delta)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0,  limit = limit, na.value = "white", oob=scales::squish) +
              geom_sf(data = countries_shp, fill = NA, colour = "grey") + 
    facet_wrap(~fcr_type) + 
  theme_minimal() +
      theme(
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) + 
    labs(caption = glue("{allocation_type}; {raw_mat}; {type}"))
            

ggsave(glue(here(this_dir, "output/plots/delta/by_material/{allocation_type}_{raw_mat}_{type}_plot.png")), width = 10, height = 8, bg = "white")

    }
  }
}

```



Lets make summary bar plots, just using economic allocation. 

```{r}
all_overlap <- all_overlap %>%
  filter(allocation == "economic")


## total AOH affected   
summary_df <- all_overlap %>%
  group_by(diet, fcr_type, allocation, ingredient) %>%
  summarise(impact_total = sum(impact_total, na.rm = TRUE)) %>%
  ungroup()

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, impact_total, FUN = function(x) sum(x)))


ggplot(summary_df, aes(x = ordered_ingredient, y = impact_total)) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  facet_grid(fcr_type ~ diet, scales = "free_y") +
    coord_flip() +
  labs(title = "Global AOH Affected (39822 species); Economic allocation", x = "Raw material and Ingredient", y = expression(paste("Total AOH Affected (", km^{2}, ")"))) + 
      theme(axis.text.x = element_text(angle = -90, hjust = 1)) # Adjust the 'angle' value as needed


## Split by class total AOH
summary_df <- all_overlap %>%
  group_by(diet, fcr_type, allocation, ingredient, spp_type) %>%
  summarise(impact_total = sum(impact_total, na.rm = TRUE)) %>%
  ungroup() 

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, impact_total, FUN = function(x) sum(x)))


muted <- color("muted")
light <- color("light")
light <- unname(c(light(9)))[c(2,3,4,6,9)]
muted <- unname(c(muted(9)))

muted_palette <- c(muted, light)


ggplot(summary_df, aes(x = ordered_ingredient, y = impact_total, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
  facet_grid(fcr_type ~ diet, scales = "free_y") +
  labs(title = "Global AOH Affected (39822 species); Economic allocation", x = "Raw material and Ingredient", y = expression(paste("Total AOH Affected (", km^{2}, ")")), fill = NULL) +
  # scale_fill_manual(values = category_colors) +
  scale_fill_manual(values = muted_palette) + 
  theme_minimal() + 
  coord_flip()  + 
    theme(axis.text.x = element_text(angle = -90, hjust = 1)) # Adjust the 'angle' value as needed



## Split by class average AOH
summary_df <- all_overlap %>%
  group_by(diet, fcr_type, allocation, ingredient, spp_type) %>%
  summarise(impact_total = mean(impact_total, na.rm = TRUE)) %>%
  ungroup() 

summary_df$ordered_ingredient <- with(summary_df, reorder(ingredient, impact_total, FUN = function(x) sum(x)))

ggplot(summary_df, aes(x = ordered_ingredient, y = impact_total, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
  facet_grid(fcr_type ~ diet, scales = "free_y") +
  labs(title = "Average AOH Affected (39822 species)", x = "Raw material and Ingredient", y = expression(paste("Average AOH Affected (", km^{2}, ")")), fill = NULL) +
    scale_fill_manual(values = muted_palette) +
  theme_minimal() + 
  coord_flip() 



## Split by class average AOH .. 
summary_df <- all_overlap %>%
  group_by(diet, fcr_type, allocation, spp_type) %>%
  mutate(species_count = n_distinct(sciname)) %>%
  summarise(nspp =  n_distinct(sciname), 
            impact_mean = mean(impact_total, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(impact_nspp_mean = impact_mean*nspp)

summary_df$spp_type <- with(summary_df, reorder(spp_type, impact_mean, FUN = function(x) sum(x)))


ggplot(summary_df, aes(x = spp_type, y = impact_mean, fill = spp_type)) +
    geom_bar(stat = "identity", position = "dodge") +
  facet_grid(fcr_type ~ diet, scales = "free") +
  theme_minimal() + 
  scale_fill_manual(values = muted_palette) + 
    labs(title = "Average AOH Affected (39822 species); Economic allocation", x = "Species Class", y = expression(paste("Average AOH Affected (", km^{2}, ")")), fill = NULL) +
  coord_flip()

```

